Cleanup scripts
pact-foundation/pact-js pull request #588
Opened 2021-01-22 04:50 UTC by TimothyJones

Looking at #584 highlighted that it's not super clear when things are triggered with our package.json scripts. I've started to clean up and consolidate them to hopefully make it clearer - thoughts welcome.

I like the guideline that the scripts are named after what they're for, not what they invoke. Like `test` instead of `jest`. Under that guideline, there's still a bit of work to do here.

(Matt, I know you don't have a lot of time atm, I'm mostly tagging you in case you're interested)

Things I'm thinking about:

* Do we need all the examples listed in package-json? We don't use those scripts in CI.
* I'm not sure whether the output of jscpd is used
* We're still generating coverage for coveralls, but aren't sending it to them (this is probably an easy fix, if we want to keep publishing those).
* I think we can also remove the `webpack` script

All thoughts and comments welcome.

2021-01-22 04:51 UTC, TimothyJones commented
@individual-it : I wanted to add you as a reviewer, but you didn't come up in the drop down for some reason. Would be keen to know what you think.

2021-01-22 06:23 UTC, mefellows commented
> Do we need all the examples listed in package-json? We don't use those scripts in CI.

I don't think so. We just want to be able run the examples as part of our CI process as a form of feature spec (and of course to make sure they are actually runnable and therefore something people can use). To be honest though, we ought to have a more dedicated feature suite - for another time.

> I'm not sure whether the output of jscpd is used

It used to be, it's quite frankly not something I'm too concerned about so I'm happy to see it removed. I think between us we'll be able to judge with PRs etc. if we're badly duplicating code. There is one area of the code base (pact-web) which could be refactored, I don't need jscpd to help me recognise that.

> We're still generating coverage for coveralls, but aren't sending it to them (this is probably an easy fix, if we want to keep publishing those).

I'm not super concerned about sending the coverage reports to coveralls (although I did think they were still working, not that I've looked recently). The main value is having some guidance around testing and %'s just give us a sense of that. Don't need coveralls to do that for us.

> I think we can also remove the webpack script

Webpack was needed by the pact-web distribution. As long as that can still build and release then the script step can go.

2021-01-22 06:25 UTC, mefellows commented
BTW the script directory cleanup looks much nicer - thanks heaps for doing it.

2021-01-22 08:01 UTC, individual-it requested changes
I cannot see where lint and format are run in CI
I actually would propose to run them directly as first steps in CI, so its very obvious for the developers

2021-01-28 04:26 UTC, TimothyJones commented on package.json
> +    "format:fix": "npm run format:base -- --fix",
You're right, I'll fix that.

2021-01-28 04:27 UTC, TimothyJones commented on package.json
> -    "deploy:prepare": "npm i --production && npm run deploy:package",
Ah, well spotted, thanks.

2021-01-28 07:04 UTC, merged